"""Add google calendar fields to user

Revision ID: 684debe30ca6
Revises: 78b58beb8455
Create Date: 2026-07-13 15:05:39.384772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '684debe30ca6'
down_revision: Union[str, None] = '78b58beb8455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.add_column('deleted_user', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('deleted_user', sa.Column('github', sa.String(), nullable=True))
    op.add_column('deleted_user', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('deleted_user', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('deleted_user', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('deleted_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('deleted_user', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_deleted_user_email'), 'deleted_user', ['email'], unique=False)
    op.drop_column('deleted_user', 'deleted_by_id')
    op.add_column('user', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('google_token_expires_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_token_expires_at')
    op.drop_column('user', 'google_refresh_token')
    op.drop_column('user', 'google_access_token')
    op.add_column('deleted_user', sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_deleted_user_email'), table_name='deleted_user')
    op.alter_column('deleted_user', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('deleted_user', 'is_active')
    op.drop_column('deleted_user', 'profile_picture')
    op.drop_column('deleted_user', 'phone')
    op.drop_column('deleted_user', 'linkedin')
    op.drop_column('deleted_user', 'github')
    op.drop_column('deleted_user', 'hashed_password')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
