"""create_deleted_user_table

Revision ID: 78b58beb8455
Revises: c452d867cfe0
Create Date: 2026-07-12 23:15:01.370179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b58beb8455'
down_revision: Union[str, None] = 'c452d867cfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_user_id'), 'deleted_user', ['id'], unique=False)
    op.create_index(op.f('ix_deleted_user_original_user_id'), 'deleted_user', ['original_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_user_original_user_id'), table_name='deleted_user')
    op.drop_index(op.f('ix_deleted_user_id'), table_name='deleted_user')
    op.drop_table('deleted_user')
    # ### end Alembic commands ###
