"""auto_sync_missing_columns

Revision ID: 9a249f678469
Revises: f49c8c168d4d
Create Date: 2026-07-16 11:06:23.051751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a249f678469'
down_revision: Union[str, None] = 'f49c8c168d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('mom_file_path', sa.String(), nullable=True))
    op.add_column('meeting', sa.Column('mom_summary', sa.String(), nullable=True))
    op.add_column('meeting', sa.Column('mom_uploaded_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meeting', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'meeting', 'user', ['mom_uploaded_by_id'], ['id'])
    op.add_column('meeting_participants', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('meeting_participants', sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'maybe', name='participantstatusenum'), nullable=True))
    op.add_column('meeting_participants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('meeting_participants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('meeting_participants', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_meeting_participants_id'), 'meeting_participants', ['id'], unique=False)
    op.create_foreign_key(None, 'task', 'meeting_extracted_tasks', ['mom_id'], ['id'])
    op.create_foreign_key(None, 'task', 'meeting', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_meeting_participants_id'), table_name='meeting_participants')
    op.drop_column('meeting_participants', 'is_deleted')
    op.drop_column('meeting_participants', 'updated_at')
    op.drop_column('meeting_participants', 'created_at')
    op.drop_column('meeting_participants', 'status')
    op.drop_column('meeting_participants', 'id')
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'mom_uploaded_by_id')
    op.drop_column('meeting', 'mom_summary')
    op.drop_column('meeting', 'mom_file_path')
    # ### end Alembic commands ###
