"""Update meeting and notification models

Revision ID: c452d867cfe0
Revises: 7f862e9d2ffa
Create Date: 2026-07-10 21:07:53.844182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c452d867cfe0'
down_revision: Union[str, None] = '7f862e9d2ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meetingtypeenum = sa.Enum('meeting', 'reminder', 'event', name='meetingtypeenum')
    meetingtypeenum.create(op.get_bind(), checkfirst=True)
    op.add_column('meeting', sa.Column('description', sa.String(), nullable=True))
    op.add_column('meeting', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('meeting', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('meeting', sa.Column('type', meetingtypeenum, nullable=True))
    op.add_column('meeting', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meeting', 'user', ['owner_id'], ['id'])
    op.drop_column('meeting', 'notes')
    op.drop_column('meeting', 'agenda')
    op.drop_column('meeting', 'time')
    op.add_column('notification', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('notification', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'is_read')
    op.add_column('meeting', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('meeting', sa.Column('agenda', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('meeting', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'owner_id')
    op.drop_column('meeting', 'type')
    op.drop_column('meeting', 'end_time')
    op.drop_column('meeting', 'start_time')
    op.drop_column('meeting', 'description')
    # ### end Alembic commands ###
